config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[index show] do
    resources :vet_dogs, only: %i[create]
  end
  resources :vet_dogs, only: :destroy do
    member do
      patch :accept
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post '/walks', to: 'walks#create'
  # Defines the root path route ("/")
  # root "posts#index"
  resources :walks, only: [:index, :create]

  resources :dogs do
    resources :walks, except: %i[update delete]
    resources :prescriptions, except: :destroy
    resources :logs
    resources :markers, only: [:create]
  end

  resources :prescriptions, only: :destroy do
    member do
      patch :complete
    end
  end
  namespace :api do
    get 'walk/latest', to: 'walks#latest'

  end

  resources :chats, only: %i[index show create new] do
    resources :messages, only: [:create]
  end

end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :walks
  has_many :logs
  has_many :prescriptions
  has_one_attached :photo
  has_many :vet_dogs, dependent: :destroy
  has_many :vet, through: :vet_dogs, source: :user
  validates :name, :breed, presence: true
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  def index
    @dogs = current_user.dogs
  end

  def new
    @dog = Dog.new
  end

  def create
    @user = current_user
    @dog = Dog.new(dog_params)
    # @dog.walk = @walk
    @dog.user = @user
    @dog.save
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render :new, status: :unprosseable_entity
    end
  end

  def show
    @pending = @dog.vet_dogs.where(status: "pending")
    @accepted = @dog.vet_dogs.where(status: "accepted")
    @prescriptions = @dog.prescriptions
    @logs = @dog.logs
  end

  def edit; end

  def update
    @dog.update(dog_params)
    redirect_to dog_path(@dog)
  end

  def destroy
    @dog.destroy
    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :medication, :condition, :breed, :date_of_birth, :weight, :photo)
  end

  def set_dog
    @dog = Dog.find(params[:id])
  end
end

app/views/dogs/_owner_show.html.erb
<div class="button-container">
<br>
  <div class="log-button">
    <%= link_to new_dog_log_path(@dog), class:"dgreen-button" do %>
    Log <i class="fa-solid fa-plus"></i>
  <% end %>
  </div>

</div>

app/views/dogs/_vet_show.html.erb
<div class="button-container">
<br>
  <div class="log-button">
  <%= link_to new_dog_prescription_path(@dog), class:"dgreen-button pup-button" do %>
    <i class="fa-solid fa-plus"></i> Prescription
  <% end %>
  </div>
</div>

app/views/dogs/edit.html.erb
  <div class="container">
  <h1>Update your puppy's info</h1>
    <div>
      <%= link_to dogs_path, class:"orange-back-link" do %>
      <i class="fa-solid fa-arrow-left"></i> My pups
      <% end %>
    </div>
    <br>
  <div class="parent container d-flex flex-column align-items-center h-100">
    <%= simple_form_for @dog do |dog| %>
      <%= dog.error_notification %>

      <div class="form-inputs">
        <%= dog.input :name %>
        <%= dog.input :breed %>
        <%= dog.input :date_of_birth %>
        <%= dog.input :weight %>
        <%= dog.input :condition %>
        <%= dog.input :medication %>

      </div>

      <div class="form-actions" >
        <p><%= dog.submit "Update", class: 'dgreen-button' do%></p>
        <% end %>
      </div>
    <% end %>

  <br>
  <br>
  <hr>
    <p>
        <%= link_to dog_path(@dog),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
          class:"remove-pup-button" do %>
            <i class="fa-solid fa-xmark"></i>  <i class="fa-solid fa-dog"></i>
        <% end %>
    </p>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="parent container h-100">
  <h1>My dogs</h1>

  <div class="container d-flex flex-column align-items-center">
    <div class="row d-flex flex-column w-100 text-center">
      <%= link_to new_dog_path, class:"dgreen-button bttn-log-index" do %>
        <span>Add new dog</span>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>

  <% @dogs.each do |dog| %>
    <div class="card-container dogs-card-container">
      <div class="card-body-details dog-card-center">
        <% if dog.photo.attached? %>
          <%= cl_image_tag dog.photo.key, gravity: "auto", crop: "fill", alt: "#{dog.name}", class:'img-square'%>
        <% else %>
          <%= image_tag "dog_placeholder.png", class:"img-square" %>
        <% end %>

        <div class="dog-name-link">
          <br>
          <h4><%= link_to dog.name, dog_path(dog), class:"orange-back-link"%></h4>
          <p class="card-text"><span class="detail-key"><i class="fa-solid fa-paw"></i> : </span> <%= dog.breed %></p>
        </div>
      </div>

      <br>
    </div>
  <% end %>

</div>

app/views/dogs/new.html.erb
<div class="parent container d-flex flex-column align-items-center h-100">
  <h1>Add your new puppy</h1>
  <%= simple_form_for @dog do |dog| %>
    <%= dog.error_notification %>

    <div class="form-inputs">
      <%= dog.input :name %>
      <%= dog.input :photo, as: :file %>
      <%= dog.input :date_of_birth %>
      <%= dog.input :breed %>
      <%= dog.input :weight %>
      <%= dog.input :condition %>
      <%= dog.input :medication %>

    </div>

    <div class="form-actions" id="nav-btn">
      <p><%= dog.submit "Add puppy", class: 'dgreen-button'%></p>
      <%= link_to dogs_path, class:"orange-back-link" do %>
      <i class="fa-solid fa-arrow-left"></i> My pups
    <% end %>
    </div>
  <% end %>
  <hr>

</div>


    <%#= link_to new_dog_path, class:"dgreen-button pup-button" do %>
<!--    <i class="fa-solid fa-plus"></i>  <i class="fa-solid fa-dog" style="color: #9d520e;"></i>-->
  <%# end %>
<!---->

app/views/dogs/show.html.erb
<div class="container">
  <h1> <%= @dog.name %>'s details</h1>
<!--  back links-->
<!--  back link for owners-->
  <% if current_user.id == @dog.user.id  %>
    <%= link_to dogs_path, class:"orange-back-link" do %>
      <i class="fa-solid fa-arrow-left"></i> My pups
    <% end %>
  <% else %>
<!--  back link for vets-->
    <%= link_to users_path, class:"orange-back-link" do %>
      <i class="fa-solid fa-arrow-left"></i> My pup patients
    <% end %>
  <% end %>

<!--  start of dog card-->
  <div class="card-container">
    <div class="dog-show-img-center">
      <% if @dog.photo.attached? %>
      <%= cl_image_tag @dog.photo.key, gravity: "auto", crop: "fill", alt: "#{@dog.name}", class:'img-square'%>
      <% else %>
      <%= image_tag "dog_placeholder.png", class:"img-square" %>
    <% end %>
    </div>
    <br>
  <h5 class="green-title"><span class="dog-name"><strong><%= @dog.name%></strong></span> </h5>
      <div class="card-body-details">
<!--start of tab section-->
<!--tab nav bar-->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item dog-logs-tab" role="presentation">
            <button class="nav-link active" id="dog-logs-tab" data-bs-toggle="tab" data-bs-target="#dog-logs-tab-pane" type="button" role="tab" aria-controls="dog-logs-tab-pane" aria-selected="true">Logs</button>
          </li>
          <li class="nav-item dog-profile-tab" role="presentation">
            <button class="nav-link" id="dog-profile-tab" data-bs-toggle="tab" data-bs-target="#dog-profile-tab-pane" type="button" role="tab" aria-controls="dog-profile-tab-pane" aria-selected="true">Profile</button>
          </li>
          <li class="nav-item dog-prescriptions-tab" role="presentation">
            <button class="nav-link" id="prescriptions-tab" data-bs-toggle="tab" data-bs-target="#prescriptions-tab-pane" type="button" role="tab" aria-controls="prescriptions-tab-pane" aria-selected="false">Prescriptions</button>
          </li>
        </ul>
<!--tab content-->
        <div class="tab-content" id="myTabContent">
<!--dog-logs tab content-->
          <div class="tab-pane fade show active" id="dog-logs-tab-pane" role="tabpanel" aria-labelledby="dog-logs-tab" tabindex="0">
            <div class="dog-log-info">
              <h6> <%= link_to dog_logs_path(@dog), class:"orange-back-link" do %>
                  See all logs
                <% end %> </h6>
                <% if current_user.id == @dog.user.id %>
                  <%= render "owner_show" %> <!-- this is the partial for the owner -->
                <% end %>
            </div>
          </div>
<!--dog-profile tab content-->
          <div class="tab-pane fade " id="dog-profile-tab-pane" role="tabpanel" aria-labelledby="dog-profile-tab" tabindex="1">
          <div class="dog-edit-profile">
            <% if current_user.id == @dog.user.id %>
              <p><%= link_to edit_dog_path, class:"orange-back-link" do%></p>
                <i class="fa-solid fa-pen-to-square"></i> Edit profile
              <% end %>
            <% end %>
          </div>
            <div class="pup-info">
              <div class="pup-info-details">
              <p class="card-text"><span class="detail-key"><i class="fa-solid fa-paw"></i> : </span> <%= @dog.breed %></p>
              <p class="card-text"><span class="detail-key"><i class="fa-solid fa-cake-candles"></i> : </span> <%= @dog.date_of_birth.strftime('%m/%d/%Y') %></p>
              <p class="card-text"><span class="detail-key"><i class="fa-solid fa-weight-scale"></i> : </span> <%= @dog.weight %> kg</p>
              </div>
              <div class="pup-health-details">
                <p class="card-text"><span class="detail-key"><i class="fa-solid fa-bandage"></i> : </span><%= @dog.condition %></p>
                <p class="card-text"><span class="detail-key"><i class="fa-solid fa-pills"></i> : </span><%= @dog.medication %></p>
                <p class="card-text"><span class="detail-key"><i class="fa-solid fa-user-doctor"></i></i> : </span>
                  <% if @dog.vet_dogs.empty? %>
                    <span>
                    <%= link_to users_path, class:"orange-back-link pup-button" do %>
                    <i class="fa-solid fa-plus"></i> <i class="fa-solid fa-stethoscope"></i> Choose vet
                    <% end %>
                    </span>
                  <% elsif @pending.present? %>
                    <% @pending.each do |vet| %>
                        <%= link_to user_path(vet), class:"vet-name-yellow" do %>
                          <%= vet.user.first_name %> (pending accept)
                        <% end %>
                      <% end %>
                  <% else %>
                    <% @accepted.each do |vet| %>
                      <% if current_user.is_vet %>
    <!--                  add a condition if vet is looking at their own profile-->
                        <%= link_to vet.user.first_name, user_path(current_user, showmyself: true), class:"vet-name-yellow" %>
                        <% else %>
                        <%= link_to vet.user.first_name, user_path(vet.user), class:"vet-name-yellow" %>
                        <% end %>
                      <% end %>
                  <% end %>
                </p>
                </div>
              </div>
          </div>
          <div class="tab-pane fade" id="prescriptions-tab-pane" role="tabpanel" aria-labelledby="prescriptions-tab" tabindex="2">
            <div class="dog-prescription-container">
            <div class="dog-see-prescription-link">
              <%= link_to dog_prescriptions_path(@dog), class:"orange-back-link" do %>
                  See all prescriptions
              <% end %>
            </div>

              <% @prescriptions.each do |prescription| %>
              <div class="dog-prescription-status-flex">
                  <p><i class="fa-solid fa-pills" style="color: #49822A;"></i> <%= prescription.medication_name %> </p>

                  <p>Status:
                  <% if prescription.completed? %>
                    <%= 'completed' %>
                  <% else %>
                    <%='ongoing' %>
                  <% end %>
                  </p>
              </div>
              <% end %>
            </div>
              <% if current_user.is_vet %>
              <%= render "vet_show" %>
              <% end %>
            </div>
          </div>
<!--end of tab section-->
        </div>



      </div>
  </div>
</div>