config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[index show] do
    resources :vet_dogs, only: %i[create]
  end
  resources :vet_dogs, only: :destroy do
    member do
      patch :accept
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post '/walks', to: 'walks#create'
  # Defines the root path route ("/")
  # root "posts#index"
  resources :walks, only: [:index, :create]

  resources :dogs do
    resources :walks, except: %i[update delete]
    resources :prescriptions, except: :destroy
    resources :logs
    resources :markers, only: [:create]
  end

  resources :prescriptions, only: :destroy do
    member do
      patch :complete
    end
  end
  namespace :api do
    get 'walk/latest', to: 'walks#latest'

  end

  resources :chats, only: %i[index show create new] do
    resources :messages, only: [:create]
  end

end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :dog
  belongs_to :user

  validates :medication_name, :start_date, :end_date, :dosage, :time_of_day, :number_of_times_per_day, presence: true
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_dog, only: %i[index new create show edit update]
  before_action :set_prescription, only: %i[show edit update destroy]
  def index
    @prescriptions = Prescription.where(dog_id: set_dog).order(created_at: :desc)
  end

  def new
    @prescription = Prescription.new
    @dog = Dog.find(params[:dog_id])
  end

  def create
    @prescription = Prescription.new(prescription_params)
    @dog = Dog.find(params[:dog_id])
    @user = current_user
    @prescription.dog = @dog
    @prescription.user = @user
    @prescription.save
    if @prescription.save
      redirect_to dog_prescription_path(@dog, @prescription)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    @dog = Dog.find(params[:dog_id])
    @prescription.update(prescription_params)
    redirect_to dog_prescription_path(@dog, @prescription)
  end

  def complete
    @prescription = Prescription.find(params[:id])
    @prescription.update(completed: true)
    redirect_to dog_prescription_path(@prescription.dog, @prescription)
  end

  def destroy
    # @prescription.dog = @dog
    if @prescription.destroy
      redirect_to dog_prescriptions_path(@prescription.dog), status: :see_other
    end
  end

  private

  def prescription_params
    params.require(:prescription).permit(:medication_name, :completed, :start_date, :end_date, :description, :dosage, :time_of_day, :number_of_times_per_day, :dog_id, :user_id)
  end

  def set_prescription
    @prescription = Prescription.find(params[:id])
  end

  def set_dog
    @dog = Dog.find(params[:dog_id])
  end
end

app/views/prescriptions/edit.html.erb
<div class="container">
<% if current_user.is_vet %>
    <%= link_to dog_prescription_path(@dog, @prescription), class:"orange-back-link" do %>
      <i class="fa-solid fa-arrow-left"></i> Back
    <% end %>
    <div class="parent container d-flex flex-column align-items-center h-100">
      <h2>Edit <%= @prescription.medication_name %> prescription</h2>
      <%= simple_form_for [@dog, @prescription] do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :medication_name %>
          <%= f.input :description %>
          <%= f.input :start_date %>
          <%= f.input :end_date%>
          <%= f.input :dosage %>
          <%= f.input :number_of_times_per_day %>
          <%= f.input :time_of_day %>
          <%= f.input :completed %>
        </div>

        <div class="form-actions" id="nav-btn">
          <p><%= f.submit "Edit prescription", class: 'dgreen-button'%></p>
        </div>
      <% end %>
      <hr>
    </div>
  <% end %>
  </div>
</div>

app/views/prescriptions/index.html.erb
<div class="container">
  <h1><%= @dog.name %>'s prescriptions</h1>
  <div>
    <%= link_to dog_path(@dog), class:"orange-back-link" do %>
      <i class="fa-solid fa-arrow-left"></i> <%= @dog.name %>
    <% end %>
  </div>
  <hr>

  <!--make completed and ongoing variables to iterate over to avoid styling clash-->
  <% completed = [] %>
  <% ongoing = [] %>
  <% @prescriptions.each do |prescription| %>
    <% if prescription.completed %>
      <% completed << prescription %>
      <% else %>
      <% ongoing << prescription %>
    <% end %>
  <% end %>
  <!--end of prescription iteration-->

  <!--if prescription is ongoing-->
  <div class="card-container">
    <div class="prescriptions-status-container">
      <h5 class="green-title"><strong>Ongoing Prescriptions</strong></h5>
      <% if ongoing.empty? %>
      <h6><em>None</em></h6>
      <% end %>
    <% ongoing.each do |prescription| %>
    <% days_left = prescription.end_date - Date.today %>
      <br>
      <div class="prescriptions-status prescription-flexbox">
          <h6 id="presctiption-name-index">
          <%= link_to dog_prescription_path(@dog, prescription), class:"ongoing-button" do %>
            <%= prescription.medication_name %>
        <% end %>
          </h6>
          <div class="prescriptions-status-details">
          <span>Prescribed on <%= prescription.created_at.strftime('%m/%d/%Y') %></span>
    <!--number of days left on prescription-->
          <% if days_left > 1 %>
          <span> <i class="fa-solid fa-arrow-right"></i> <em><%= days_left.to_i %> days left</em></span>
            <% else %>
          <span>  <i class="fa-solid fa-arrow-right"></i><em><%= days_left.to_i %> day left</em></span>
            <% end %>
  <!--end of days left if statement-->
          </div>
      </div>
    <% end %>
  </div>
 </div>
  <!--end of ongoing prescription iteration-->
<br>
  <!--if prescription is complete-->
<div class="card-container">

  <div class="prescriptions-status-container">
      <h5 class="green-title"><strong>Completed Prescriptions</strong></h5>
      <% if completed.empty? %>
        <h6><em>None</em></h6>
      <% end %>
    <% completed.each do |prescription| %>
      <div class="prescriptions-status">
      <h6>
        <%= link_to dog_prescription_path(@dog, prescription), class:"orange-back-link" do %>
          <%= prescription.medication_name %>
        <% end %>
      </h6>
      </div>
    <% end %>
  </div>
</div>
  <!--end of completed prescription iteration-->

<!--  add prescription button for vet-->
<% if current_user.is_vet %>
  <div class="button-container">
<br>
  <div class="log-button">
  <%= link_to new_dog_prescription_path(@dog), class:"dgreen-button pup-button" do %>
    <i class="fa-solid fa-plus"></i> Prescription
  <% end %>
  </div>
</div>
<% end %>
</div>

app/views/prescriptions/new.html.erb
<div class="container">
<% if current_user.is_vet %>
  <div>
      <%= link_to dog_prescriptions_path(@dog), class:"orange-back-link" do %>
      <i class="fa-solid fa-arrow-left"></i> Prescriptions
      <% end %>
  </div>
  <br>
    <div class="parent d-flex flex-column align-items-center h-100">
      <h2 class="green-title">New prescription for <%= @dog.name %></h2>
      <%= simple_form_for [@dog, @prescription] do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :medication_name %>
          <%= f.input :description %>
          <%= f.input :start_date %>
          <%= f.input :end_date%>
          <%= f.input :dosage %>
          <%= f.input :number_of_times_per_day %>
          <%= f.input :time_of_day %>
          <%= f.input :completed %>
        </div>

        <div class="form-actions" id="nav-btn">
          <p><%= f.submit "Add prescription", class: 'dgreen-button'%></p>
        </div>
      <% end %>
      <hr>
    </div>
  <% end %>
  </div>
</div>

app/views/prescriptions/show.html.erb
<div class="container">
<div>
  <%= link_to dog_prescriptions_path, class:"orange-back-link" do %>
    <i class="fa-solid fa-arrow-left"></i> All prescriptions
  <% end %>
</div>
<br>
  <div class="card-container prescription-show-info">
  <!--prescription details-->
  <h2 class="green-title"><strong><%= @prescription.medication_name %></strong></h2>
  <h5><span class="detail-key"><i class="fa-solid fa-pen"></i> :</span> Prescribed on <%= @prescription.created_at.strftime('%m/%d/%Y') %></h5>
  <h5><span class="detail-key"><i class="fa-solid fa-tablets"></i> :</span> <%= @prescription.description %></h5>
  <h5><span class="detail-key"><i class="fa-solid fa-syringe"></i> :</span> <%= @prescription.dosage %></h5>
  <h5><span class="detail-key"><i class="fa-solid fa-clock"></i> :</span> <%= @prescription.time_of_day %></h5>
  <% if @prescription.number_of_times_per_day > 1 %>
  <h5><span class="detail-key"><i class="fa-solid fa-rotate-right"></i> :</span> Take <%= @prescription.number_of_times_per_day%> doses a day</h5>
  <% else %>
  <h5><span class="detail-key"><i class="fa-solid fa-rotate-right"></i> :</span> Take <%= @prescription.number_of_times_per_day%> dose a day</h5>
  <% end %>
    <% days = @prescription.end_date - @prescription.start_date %>
    <% if days == 1 %>
    <h5><span class="detail-key"><i class="fa-solid fa-calendar"></i> :</span> Take for <%= days.to_i %> day</h5>
      <% else %>
    <h5><span class="detail-key"><i class="fa-solid fa-calendar"></i> :</span> Take for <%= days.to_i %> days</h5>
    <% end %>

  <!--prescription status -->
    <% if %>
    <% @prescription.completed? %>
      <h5><span class="detail-key"> <strong>Status:</strong> </span>This prescription is complete</h5>
      <% else %>
      <% days_left = @prescription.end_date - Date.today %>
        <% if days_left > 1 %>
      <h5><span class="detail-key"><strong>Status:</strong></span> There is <%= days_left.to_i %> days left</h5>
        <% else %>
      <h5><span class="detail-key"><strong>Status:</strong></span> There is <%= days_left.to_i %> day left</h5>
        <% end %>
    <% end %>
  </div>
<!--  mark as complete -->
<% if !current_user.is_vet && !@prescription.completed %>
<div class="mark-complete-container">
  <div class="mark-complete">
    <h6>
    <%= link_to complete_prescription_path(@prescription), data: {turbo_method: :patch} do %>
      Mark as complete <i class="fa-solid fa-check"></i>
    <% end %>
    </h6>
  </div>
</div>
<% end %>

<!--  edit/remove if user is vet-->
<% if current_user.is_vet %>

<div class="button-container">
<br>
  <div class="button-flexbox">
    <%= link_to edit_dog_prescription_path(@dog, @prescription), class:"dgreen-button update-pup-button" do%>
      <i class="fa-solid fa-pen-to-square"></i> Edit
    <% end %>
    <%= link_to prescription_path(@prescription),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
      class:"remove-prescription-button" do %>
      <i class="fa-solid fa-xmark"></i> Remove
    <% end %>
  </div>
</div>
<% end %>
</div>
</div>