config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[index show] do
    resources :vet_dogs, only: %i[create]
  end
  resources :vet_dogs, only: :destroy do
    member do
      patch :accept
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post '/walks', to: 'walks#create'
  # Defines the root path route ("/")
  # root "posts#index"
  resources :walks, only: [:index, :create]

  resources :dogs do
    resources :walks, except: %i[update delete]
    resources :prescriptions, except: :destroy
    resources :logs
    resources :markers, only: [:create]
  end

  resources :prescriptions, only: :destroy do
    member do
      patch :complete
    end
  end
  namespace :api do
    get 'walk/latest', to: 'walks#latest'

  end

  resources :chats, only: %i[index show create new] do
    resources :messages, only: [:create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dogs
  has_many :vet_dogs
  has_many :patients, through: :vet_dogs, source: :dog
  has_many :prescriptions
  has_many :chats
  has_many :walks
  has_one_attached :photo
  # has_many :walks, through: :dogs
  # has_many :logs, through: :dogs


  # validates :is_vet, presence: true
  # validates :opening_time, :closing_time, presence: true if ?? (after create validation or javascript validation?)

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @vets = User.where(is_vet: true)
    @owners = User.where(is_vet: false)
    @patients = current_user.patients.joins(:vet_dogs).where(vet_dogs: { status: "accepted" })
    # we get dogs from our association through vet_dogs
  end

  def show
    @user = User.find(params[:id])
    @vet_dog = VetDog.new
    @no_vet = current_user.dogs.left_joins(:vet_dogs).where(vet_dogs: { id: nil })
    @pending = current_user.vet_dogs.where(status: "pending")
    @accepted = current_user.vet_dogs.where(status: "accepted")
  end
end

app/views/users/_cards_for_owners.erb
<div class="container">
<h1>Select your vet</h1>

<!--<div>-->
    <%#= link_to root_path, class:"orange-back-link" do %>
<!--      <i class="fa-solid fa-arrow-left"></i> Home-->
    <%# end %>
<!--  </div>-->
  <div class="row">
  <% @vets.each do |vet| %>
      <div class="col-sm-6 col-md-4 col-lg-3 mt-3 vet-owner-cards">
        <div class="card-container vets-cards-links">
          <%= link_to user_path(vet)do %>
            <div class="title-flexbox">
              <div class="green-title card-nav-title">
                <h3 >Dr. <%= vet.first_name%> <%= vet.last_name %></h3>
              </div>
              <div class="card-nav-img img-rounded">
                <% if vet.photo.attached? %>
                  <%= cl_image_tag vet.photo.key, gravity: "auto", crop: "fill", alt: "#{vet.first_name}", class:'img-rounded'%>
                <% else %>
                  <%= image_tag "profile_placeholder", class:"img-rounded" %>
              <% end %>
              </div>
            </div>
            <div class="card-body-details vet-info-flexbox">
              <div class="vet-info-flex-item">
                <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-house-user"></i> : </span><%= vet.address %></p>
                <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-phone"></i> : </span> <%= vet.mobile_number %></p>
              </div>
              <div class="vet-info-flex-item">
                <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-door-open"></i> : </span> <%= vet.opening_time.strftime('%I:%M:%S %p') %> </p>
                <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-door-closed"></i> : </span> <%= vet.closing_time.strftime('%I:%M:%S %p') %> </p>
              </div>
            </div>

  <br>
        </div>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_cards_for_vets.erb
<h1>All your clients</h1>
<!--  <div>-->
    <%#= link_to root_path, class:"orange-back-link" do %>
<!--      <i class="fa-solid fa-arrow-left"></i> Home-->
    <%# end %>
<!--  </div>-->


<div class="row">
<% @patients.each do |dog| %>
    <div class="col-sm-6 col-md-4 col-lg-3 mt-3 vet-owner-cards">
      <div class="card-container">
            <%= link_to dog_path(dog), class:"dyellow-button" do %>
        <div class="title-flexbox">
              <div class="green-title card-nav-title">
                <h3 class="card-title"><%= dog.name  %> </h3>
              </div>
              <div class="card-nav-img">
                  <% if dog.photo.attached? %>
                    <%= cl_image_tag dog.photo.key, gravity: "auto", crop: "fill", class: "img-rounded", alt: "#{dog.name}" %>
                  <% else %>
                    <%= image_tag "dog_placeholder.png", class:"img-rounded" %>
                <% end %>
              </div>
            </div>
              <div class="card-body-details">
                <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-user"></i> : </span> <strong><%= link_to dog.user.first_name, user_path(dog.user), class:"owner-name" %></strong> </p>
                <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-house-user"></i> : </span> <%= dog.user.address %></p>
                <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-phone"></i> : </span> <%= dog.user.mobile_number %> </p>
              </div>

            <% end %>



      </div>

    </div>
  <% end %>
</div>

app/views/users/_owner_details.html.erb
<h1><%= @user.first_name %>'s details</h1>

<% if current_user.is_vet %>
<div>
  <%= link_to users_path, class:"orange-back-link" do %>
    <i class="fa-solid fa-arrow-left"></i> Patients
  <% end %>
</div>
<% else %>
<div class="owner-logout-flexbox">
  <div class="owner-logout-flex-item">
    <%= link_to dogs_path, class:"orange-back-link" do %>
      <i class="fa-solid fa-arrow-left"></i> My pups
    <% end %>
  </div>
  <div class="owner-logout-flex-item">
    <% if !current_user.is_vet && params[:showmyself].present? %>
    <div class="orange-back-link">
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    </div>
  <% end %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col mt-3 mb-3">
    <div class="card-container">
        <div class="center-img">
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, gravity: "auto", crop: "fill", alt: "#{@user.first_name}", class:'img-square'%>
      <% else %>
        <%= image_tag "profile_placeholder.png", class:"img-square" %>
    <% end %>
        </div>
        <br>
          <h5 class="green-title"><strong><%= @user.first_name %> <%= @user.last_name %></strong> </h5>
            <div class="card-body-details">
              <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-house-user"></i> </span><%= @user.address %></p>
              <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-phone"></i> : </span> <%= @user.mobile_number %> </p>
              <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-at"></i> : </span> <%= @user.email %> </p>
            </div>
    </div>
  </div>
</div>

<% if current_user.is_vet && !params[:showmyself].present?%>
    <% if @user.dogs.length == 1 %>
        <div class="dgreen-title">
          <h5><span class="owner-pet-title "><strong><%= @user.first_name%>'s pup:</strong></span></h5>
        </div>
        <div class="row">
          <div class="col mt-1 mb-1">
            <div class="card-container">
                <div class="title-flexbox">
                <div class="card-body-details">
                  <div class="pup-info">
                    <div class="pup-info-details">
                      <p class="card-body-text"><span class="detail-key"><strong>Name: </strong></span><%= link_to @user.dogs.first.name, dog_path(@user.dogs.first) %></p>
                      <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-paw"></i> : </span><%= @user.dogs.first.breed %></p>
                    </div>
                  </div>
                </div>
                  <div class="dog-show-img-center">
                  <% if @user.dogs.first.photo.attached? %>
                    <%= cl_image_tag @user.dogs.first.photo.key, gravity: "auto", crop: "fill", class: "small-img-square", alt: "#{@user.dogs.first.name}" %>
                  <% else %>
                    <%= image_tag "dog_placeholder.png", class:"small-img-square" %>
                  <% end %>
                  </div>
                </div>
            </div>
          </div>
        </div>
    <% else %>
    <div class="dgreen-title">
      <h5><span class="owner-pet-title"><strong><%= @user.first_name%>'s pups:</strong></span></h5>
    </div>
        <div class="row">
          <%@user.dogs.each do |pet|%><!---->
            <div class="col-sm-12 mt-1 mb-1">
              <div class="card-container">
                  <div>
                    <div class="title-flexbox">
                      <div class="pup-vet-info">
                          <h6 class="card-body-text" ><%= link_to pet.name, dog_path(pet), class:"dog-name-link" %></h6>
                          <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-paw"></i> : </span><%= pet.breed %></p>
                      </div>
                      <div class="card-nav-img">
                      <% if pet.photo.attached? %>
                        <%= cl_image_tag pet.photo.key, gravity: "auto", crop: "fill", class: "small-img-square", alt: "#{pet.name}" %>
                      <% else %>
                        <%= image_tag "dog_placeholder.png", class:"small-img-square" %>
                      <% end %>
                      </div>
                    </div>
                  </div>
              </div>
          </div>
            <% end %>
        </div>
    <% end %>
  <% end %>

app/views/users/_owners_cards.html.erb
<h1>Select your vet</h1>
<div class="row">
<% @vets.each do |vet| %>
    <div class="col col-md-4 mt-3 mb-3">
      <div class="card">
        <img src="" class="card-img-top" alt="...">
        <div class="card-body">
          <div class="d-flex justify-content-between mb-3">
            <div>
              <h5 class="card-title">DR. <%= vet.first_name%> <%= vet.last_name %></h5>
              <p class="card-text">Cabinet Address: <%= vet.address %></p>
              <p class="card-text">Contact number: <%= vet.mobile_number %></p>
              <p class="card-text">Opening Time: <%= vet.opening_time %> </p>
              <p class="card-text">Closing Time: <%= vet.closing_time %> </p>
            </div>
          </div>

          <div class="d-flex justify-content-between" >
            <div>
            <%= link_to 'Details', user_path(vet) %>
            </div>
            <div>
            <%= link_to 'Back', root_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_vet_details.html.erb
<div class="container">
  <h1> Dr.<%= @user.last_name %>'s details</h1>
  <br>
  <!--Back link for vets + logout button-->
  <% if current_user.is_vet %>
      <div class="owner-logout-flexbox">
        <div class="owner-logout-flex-item">
          <%= link_to users_path, class:"orange-back-link" do %>
          <i class="fa-solid fa-arrow-left"></i> Patients
          <% end %>
        </div>
        <div class="owner-logout-flex-item">
          <% if params[:showmyself].present? %>
          <div class="orange-back-link">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        <% end %>
        </div>
  </div>
      </div>

  <% else %>
      <div>
  <!--Back link for owners-->
        <%= link_to users_path, class:"orange-back-link" do %>
        <i class="fa-solid fa-arrow-left"></i> Vets
        <% end %>
      </div>
  <% end %>
  <div class="card-container">
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, gravity: "auto", crop: "fill", alt: "#{@user.first_name}", class:'img-square'%>
        <% else %>
          <%= image_tag "profile_placeholder.png", class:"img-square" %>
      <% end %>
  <div class="vet-profile-info">
    <h5 class="card-title green-title"><strong><%= @user.first_name %> <%= @user.last_name %></strong> </h5>
    <div class="card-body-details">
      <div class="vet-info-flexbox">
        <div class="vet-info-flex-item">
          <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-house-user"></i> : </span> <%= @user.address %></p>
          <p class="card-body-text"><span class="detail-key"><i class="fa-solid fa-phone"></i> : </span> <%= @user.mobile_number %> </p>
        </div>
        <div class="vet-info-flex-item">
          <p class="card-body-text"> <span class="detail-key"><i class="fa-solid fa-door-open"></i> : </span> <%= @user.opening_time.strftime('%I:%M:%S %p') %> </p>
          <p class="card-body-text"> <span class="detail-key"><i class="fa-solid fa-door-closed"></i> : </span> <%= @user.closing_time.strftime('%I:%M:%S %p') %> </p>
        </div>
      </div>
    </div>
  </div>

    <hr>
  <!--  Client request section for vets -->
  <% if current_user.is_vet %>
    <% if !@accepted.empty? %>
      <% if @accepted.length > 1 %>
        <h6>You currently have <%= @accepted.length %> clients</h6>
        <% else %>
        <h6>You currently have <%= @accepted.length %> clients</h6>
        <% end %>
    <% end %>
    <% if !@pending.empty? %>
    <hr>
        <h6>Pending patient requests</h6>
          <% @pending.each do |request| %>
            <div class="card-body-details request-flex">
              <div class="client-request">
              <p class="card-body-text">
                <span class="detail-key"><i class="fa-solid fa-user"></i> : </span> <%= request.dog.user.first_name %> <%= request.dog.user.last_name %> |
                <span class="detail-key"><i class="fa-solid fa-dog"></i> : </span> <%= request.dog.name %>
              </p>
              </div>
              <div class="accept-reject">
                <span class="accept-button">
                  <%= link_to accept_vet_dog_path(request), data: {turbo_method: :patch} do %>
                    <i class="fa-solid fa-check"></i>
                  <% end %>
                </span>
                <span class="reject-button">
                  <%= link_to vet_dog_path(request), data: {turbo_method: :delete} do%>
                    <i class="fa-solid fa-xmark"></i>
                  <% end %>
                </span>
                </div>
              </div>
          <% end %>
        <% end %>
  <% end %>

  <!--client request form for owners-->
  <% if !current_user.is_vet && @no_vet %>

    <div class="new-vet-form">
    <%= simple_form_for [@user, @vet_dog] do |f| %>
      <%= f.error_notification %>
        <div class="vet-form-inputs">
          <%= f.association :dog, :label => "Please select dog:", collection: @no_vet%>
        </div>
        <div class="button-flexbox">
          <div class="vet-form-actions">
            <p><%= f.submit "Send request to vet", class: 'dyellow-button'%></p>
          </div>

    <% end %>
  <% end %>

        </div>
    </div>

  </div>
</div>

app/views/users/_vets_cards.html.erb
<h1>All your clients</h1>
<div class="row">

<% @patients.each do |dog| %>
    <div class="col mt-3 mb-3">
      <div class="card">
        <img src="" class="card-img-top" alt="...">
        <div class="card-body">
          <div class="d-flex justify-content-between mb-3">
            <div>
              <h5 class="card-title"><%= dog.name  %> </h5>
              <p class="card-text">Owner: <%= dog.user.first_name %> </p>
              <p class="card-text">Address: <%= dog.user.address %></p>
              <p class="card-text">Mobile number: <%= dog.user.mobile_number %> </p>
            </div>
          </div>

          <div class="d-flex justify-content-between" >
            <div>
            <%= link_to 'Details', user_path(dog.user) %>
            </div>
            <div>
            <%= link_to 'Back', root_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
<% if current_user.is_vet %>
  <%= render "cards_for_vets" %>
<% else %>
  <%= render "cards_for_owners" %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
<% if current_user.is_vet && params[:showmyself].present?%>
  <%= render "vet_details" %>
<% elsif current_user.is_vet%>
  <%= render "owner_details" %>
  <% elsif !current_user.is_vet && params[:showmyself].present?%>
    <%= render "owner_details" %>
<% else %>
<%= render "vet_details" %>
<% end %>
</div>