config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[index show] do
    resources :vet_dogs, only: %i[create]
  end
  resources :vet_dogs, only: :destroy do
    member do
      patch :accept
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post '/walks', to: 'walks#create'
  # Defines the root path route ("/")
  # root "posts#index"
  resources :walks, only: [:index, :create]

  resources :dogs do
    resources :walks, except: %i[update delete]
    resources :prescriptions, except: :destroy
    resources :logs
    resources :markers, only: [:create]
  end

  resources :prescriptions, only: :destroy do
    member do
      patch :complete
    end
  end
  namespace :api do
    get 'walk/latest', to: 'walks#latest'

  end

  resources :chats, only: %i[index show create new] do
    resources :messages, only: [:create]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<% if current_user.is_vet %>
<div class="menu-sticky">
  <ul id="menuItems">
    <li> <%= link_to users_path do %>
      <i class="fa-solid fa-dog"></i>
    <% end %></li>
    <li> <%= link_to user_path(current_user, showmyself: true) do %>
      <i class="fa-solid fa-user"></i>
    <% end %></li>
  </ul>
</div>
  <% else %>
  <div class="menu-sticky">
  <ul id="menuItems">
    <li> <%= link_to chats_path do %>
      <i class="fa-solid fa-comments"></i>
    <% end %></li>
    <li> <%= link_to users_path do %>
      <i class="fa-solid fa-stethoscope"></i>
    <% end %></li>
    <li> <%= link_to dogs_path do %>
      <i class="fa-solid fa-dog"></i>
    <% end %></li>
    <li> <%= link_to walks_path do %>
      <i class="fa-solid fa-shoe-prints"></i>
    <% end %></li>
    <li> <%= link_to user_path(current_user, showmyself: true) do %>
      <i class="fa-solid fa-user"></i>
    <% end %></li>
  </ul>
</div>
<% end %>
<div class="spacer">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Logo1.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>